### ISSUE TITLE
theme file name visible

### ISSUE THREAD

**Issue by troutacular** [wp-repository/wpmu-theme-usage-info#7]
Enhancement Request:

display the folder name of the theme so if you have to clean up an older wpmu install several different folders but individuals adding the same theme name, you can view the folder path to know which one is actually being used/unused.

**Comment by cfoellmann** [comment]
I just release a big update. The data is now displayed in the core table on the themes.php page.
I am not sure if this plugin is the best place to put this. But I will keep it open and thereby in mind, hopefully.

**Comment by troutacular** [comment]
Great- thank you!
